# Generated by Django 5.2.10 on 2026-03-05 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_aula', models.CharField(max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('resumo', models.TextField()),
                ('dificuldade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
            ],
        ),
    ]
